### ISSUE TITLE
Touch box "off" when trying to trim video

### ISSUE THREAD

**Issue by blurtime** [fulldecent/FDTake#109]
Hi @fulldecent,

I've been using the following lines to enable users to trim their videos:

    self.imagePicker.allowsEditing = self.allowsEditing
    if self.allowsEditing == true {
        self.imagePicker.videoQuality = UIImagePickerControllerQualityType.typeHigh
        self.imagePicker.videoMaximumDuration = 12.5
    }

Since iOS 11, I've been encountering the following issue however: [My question regarding this issue on stackoverflow](https://stackoverflow.com/questions/47847765/imagepickers-videomaximumduration-left-trim-bars-touch-box-off). I checked whether other apps were encountering the same problem (e.g WhatsApp) and they did not. Do you have any idea why this occurs? I would really like to keep using this.

**Comment by fulldecent** [comment]
Thank you for sharing this issue. I believe this is entirely upstream and out of scope for FDTake, so I will close the issue here. 

I've starred your SO issue and will read more there. Please add a `FDTake` tag there if it is relevant.

If you can create a minimized test case then I think SO will definitely get you an answer. Also, I do know that Apple engineers are VERY active on SO and they will get back to you. But they are on vacation now until the end of the year.

**Comment by blurtime** [comment]
Ok, I understand. If you want to see what it looks, you can watch a small clip on youtube now. Would really appreciate if you could take a look at it!
