### ISSUE TITLE
Updated from version 1.0.0, app won't compile

### ISSUE THREAD

**Issue by WedgeSparda** [fulldecent/FDTake#116]
Hi, I want to updated an old project written in Objective-C using this library, but I'm getting a lot of compile errors like:

`Property 'allowsVideo' not found on object of type 'FDTakeController *'`
`Property 'allowsEditing' not found on object of type 'FDTakeController *'`
`No visible @interface for 'FDTakeController' declares the selector 'present'`

Did you drop support for Obj-C? I tried to stay with version 1.0.0 but then I get this error:

`SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'FDTake')`

**Comment by fulldecent** [comment]
Yes, the latest supported versions are now written in Swift, targeting version 5. There may be some backwards compatibility on Swift to earlier version but I am not sure how that works and I recommend anybody using Swift to target the latest version because it is easy to upgrade and Apple will start to support dynamic link Swift, which will half app sizes.

Each update of FDTake bumped the major version number when breaking changes were introduced (or at least we tried to follow this rule).
