### ISSUE TITLE
FDTakeController add a property Tag 

### ISSUE THREAD

**Issue by SeanChense** [fulldecent/FDTake#51]
`@property (nonatomic, copy) NSString *tag;`
so,we can distinguish them when using 
`- (void)takeController:(FDTakeController *)controller gotPhoto:(UIImage *)photo withInfo:(NSDictionary *)info` .I will take two photos in a viewcontroller

**Comment by fulldecent** [comment]
Because the controller is sent back in the delegate method, you are able to distinguish.

Here is how I have done so in other projects:

 * Create a dictionary for Object -> Tag number
 * Set tag using dict `[[NSValue valueWithNonretainedObject:lesson]] = tag`
 * Retrieve tag using `[[NSValue valueWithNonretainedObject:lesson]]`

Closing for now, but may reopen if this is a common issue and this solution is not working
